# Generated by Django 2.2.4 on 2019-10-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/images/')),
                ('brothers', models.ManyToManyField(related_name='_character_brothers_+', to='ancient_greek.Character')),
                ('children', models.ManyToManyField(related_name='_character_children_+', to='ancient_greek.Character')),
                ('father', models.ManyToManyField(related_name='_character_father_+', to='ancient_greek.Character')),
                ('linked_to', models.ManyToManyField(related_name='_character_linked_to_+', to='ancient_greek.Character')),
                ('mother', models.ManyToManyField(related_name='_character_mother_+', to='ancient_greek.Character')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancient_greek.Nature')),
                ('sisters', models.ManyToManyField(related_name='_character_sisters_+', to='ancient_greek.Character')),
            ],
        ),
    ]
