# Generated by Django 2.2.4 on 2019-10-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancient_greek', '0002_auto_20191008_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='media/images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.AddField(
            model_name='character',
            name='images',
            field=models.ManyToManyField(blank=True, to='ancient_greek.Images'),
        ),
    ]
