# Generated by Django 2.2.4 on 2019-10-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancient_greek', '0003_auto_20191008_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Gallery',
        ),
    ]
