# Generated by Django 2.2.4 on 2019-10-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancient_greek', '0004_auto_20191008_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Image',
        ),
    ]
